apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: temp
    user: admin
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: password
